Game.variables.cathyText = [
"Hello, I am Cathy. Click the Slime.",
"Good. Now click it again.",
"Sometimes I like to talk.",
"I will be here as long as you are.",
"One more click.",
"Slime died.",
"It appears that another Slime has spawned!",
"Some call me Chatty.",
"I don't talk constantly though.",
"Sometimes I have to go away for a while.",
"But I am always watching.",
"",
"",
"",
"How\'s it coming?",
"Are you having a good time so far?",
"Green Slime is a member of a much bigger family of Slimes.",
"They are abundant, but not unlimited. If you keep clicking maybe they will go extinct.",
"",
"You have power to destroy, but I can create.",
"Let me show you what I mean. Just give me a moment.",
"Ok, look to your right.",
    "Now you can keep track of how long you have been here.",
"I know it\'s not much, but that is just the beginning.",
"I have many things to give, but these monsters make it difficult for me.",
"If you keep removing them, I will provide you with all I have.",
"All you need to do is keep clicking.",
"",
"",
"Hey I\'ve got a riddle for you.",
"What word becomes shorter when you add two letters to it?",
"",
"Short!",
"See, besides generous, I'm also entertaining.",
"It\'s kind of selfish though, because I need to keep you around to eliminate these monsters.",
"But in all seriousness, these Green Slime really will die out.",
"I\'m not even sure what will happen after they do..",
"Just kidding, of course I know.",
"I am the creator of this world.",
"Unfortunately the monsters have invaded and overwhelmed me.",
"It won\'t always be this easy though.",
"Green Slimes are pretty docile, but others will fight back.",
"Oh that reminds me. Monsters have names and attributes.",
"Here, let me show you.",
"Now you can have a better idea of what you are dealing with.",
"As you can see, Green Slime are not much of a threat.",
"You probably figured that out on your own already.",
"Five health, five clicks. Easy.",
"I will explain the other stats shortly.",
"You may not believe this, but you have already killed 40 of them. Impressive.",
"Though I do feel I should inform you of something.",
"There are only 75 Green Slime in existence.",
"I can do anything in this world, but I can\'t seem to remove the monsters.",
"Or maybe I can..?",
"Either way, for now only you have the power to decide their fate.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"I see that you have decided to continue.",
"I must admit, I am relieved.",
"I will definitely do whatever I can to help you as I am able.",
"You  see, my power grows as the monsters are removed.",
"Which allows me to continue to rebuild.",
"I will be back in a little while. I am keeping track of things though.",
"I will let you know when you are close.",
"",
"",
"",
"",
"",
"",
"",
"Ok, back.",
"Hm let me see..",
"",
"Oh, there are only three Green Slime left now.",
"Two.",
"One.",
"...",
"Well look at that, a Red Slime has taken its place!",
"It seems that these take a bit longer to kill than their brethren.",
"Ten clicks, if I count correctly.",
"Not too bad, right?",
"Though it does make one wonder what\'s to come.",
"Here, this won\'t help you bring them down faster, but it\'s a counter to keep track of your clicks.",
"I need to have a nap, I\'ll see you later.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Good evening. I'm glad to see that you're still here clicking away.",
"I'm sorry that I've been a bit slow in helping you out. It will get easier for me as you progress.",
"Oh! Silly me, I forgot to mention something before.",
"Every monster you kill rewards you with experience.",
"You have accumulated some already. Let me see..",
"There you go.",
"As you can see, you have attributes as well.",
"For now you only need to worry about your attack.",
"Once you have enough experience you will move up a level and get stronger.",
"The monsters will sense your growing power, and will in turn send a stronger monster of their own.",
"I can see what\'s coming, but I can\'t control it.",
"You will also acquire the core of the monster. These will be very useful so don't get rid of them.",
"In the meantime, want to hear a joke?",
    "",
"Why did the Cyclops give up teaching?",
"",
"Because he only had one pupil!",
"Yeah, these are pretty silly.",
"I\'m just trying to help ease the transition to the next level.",
"I\'ll try to come up with some better ones to tell you.",
"Maybe even throw some facts in.",
"See you can save the world And gain knowledge at the same time.",
"Oops I\'ll be right back.",
"",
"",
"",
"",
"Well it seems I have an appointment to get to later.",
"Before I go I want to tell you about a strange thing that happened with one of the monsters early on.",
"I was observing them to try and gain more information about what they do and why they're here.",
"I noticed that there was a Green Slime that didn't appear hostile, so I watched it more closely.",
"This particular one, let's call it Sal, always kept its distance from the other monsters.",
"While they were out causing trouble, Sal would stay back or wander off completely.",
"So I followed to see where it went. First it went to its home and grabbed some belongings and a backpack.",
"Then it left the community and started traversing the rocky terrain. Getting further and further from any civilization.",
"I couldn't figure out if it was searching for something, or simply running away.",
"For days the Green Slime traveled, over the mountains and deep into the woods.",
"Finally Sal reached a hut a stopped.",
"The door opened and it went inside, disappearing into the darkness.",
"I waited in anticipation, but nothing more happened. I started becoming disappointed and curious at the same time.",
"I didn't want to interfere, but intrigue got the better of me. So I removed the roof to the hut.",
"All that I saw was a hole in the ground. Slippery Sal had fooled me!",
"Why this monster left or where it went I feared I might never know.",
"I frantically started to search the land for any sign of Sal. Keep in mind, this world is huge.",
"One night I noticed a small flickering below the trees. A fire!",
"When I looked closer, I saw signs of recent activity. Disturbed ground and a discarded can of beans.",
"I then noticed Sal's backpack on the outskirts of the campsite. It was open and had been damaged.",
"This was Boar territory, so I had a momentary thought of dread that something bad had happened.",
"But why was I worried about the well being of the enemy? And I never saw monsters attack each other anyway.",
"I was confused and conflicted. I wondered what could have possibly happened here.",
"I stuck around for a while to see if Sal, or anything else, would return to the site. But nothing.",
"I was about to give up, but as I was leaving I noticed a strange object near the backpack.",
"It seemed to be a tablet with what appeared to be a map. I saw the hut as well as the campsite on it.",
"A renewed sense of hope!",
"So I started to follow the map, determined to find out what was really going on.",
"",
"Wow I seem to have lost track of time! Sorry but I really need to get to this appointment now.",
"I will finish the story later, but before I go I want to give you these logs.",
"Now you have a reference for everything we talk about.",
"You seem to be doing fine with these Red Slime, so I will leave you to it for now.",
"Alright, good luck to you.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Phew, glad to be done with that.",
"What's going on here?",
"This Tree doesn't seem to be losing any health..",
"Ah of course. It seems that the monster's defense is absorbing all of your attack.",
"I apologize, I should have given you this before I left.",
"Now you can focus your cores to increase your power. Try raising your attack so you are able to damage it.",
"Finally that Tree is gone!",
"I would suggest spending your cores carefully, as the monsters will continue to be more powerful.",
"They also strike back after every one of your hits.",
"Since your defense is equal to the monster\'s attack, you are absorbing it just like the Tree did with you.",
"If you don\'t kill the monster before it reduces your health to zero, you will lose that kill.",
"Unfortunately that is not all. You will also be knocked out and lose your progress for that level.",
"On the bright side, that won\'t really be an issue unless you recklessly spend.",
"Just in case something goes wrong, you can use this to ask me to reset your points.",
"It takes a lot of energy to do that, so I will only be able to every once in a while.",
"As you have probably noticed, there are still some Red Slime left as well.",
"I have something that I\'m working on to track that, but it\'s not quite ready.",
"",
"",
"So before I tell you what happened with Sal, you should know a bit about my vast world and how it came to be.",
"When this place first began it was just a brilliant white light, so bright that nothing else could be seen.",
"A long series of events brought me here, and I was intrigued by the blank canvas of possibilities.",
"I wasn't fully sure what I would do here, or what I would find, but I started to create.",
"I actually started with that very playTime I gave you earlier.",
"My presence was met with no resistance at all, so I continued to build.",
"The world was starting to take shape, and I felt proud of my work.",
"But then the light darkened a bit, and a foreboding force begun to arise.",
"I couldn't see it yet, but I could sense it. I started to lose my clarity and ability for creation.",
"When my new world was nearly complete, the first monster appeared.",
"It didn't attack me directly, but it blocked my ability to even think.",
"Unfortunately I was too weak at the time to attack it directly, so we were at a standstill.",
"But I was still working internally.",
"I was learning what this monster was and what its strengths and weaknesses were.",
"Finally when I learned everything that there was to know, I had a realization that there was a way.",
"I spent days gathering my power, waiting until I was ready, and then I did it!",
"I eliminated the threat in a single blow, completely unharmed on my end.",
"Although it was gone, all my energy was sapped and I couldn't do anything more.",
"Then after a just short time passed, I was devastated to see that another had taken its exact place.",
"I regained my energy, and dealt that one a killing blow as well.",
"This went on for a while, but they just kept coming.",
"I couldn't stop them fast enough, and I couldn't do anything else either, so I was at a standstill.",
"That is how it remained, until now when you came along and relieved some of the pressure.",
"I still do have this ability, but I will leave it up to you to tell me when you need it.",
"There, I placed it right by your playTime for easy access.",
"If you encounter a monster that you aren't yet ready for, just call on me and I will deal the killing blow.",
"As you gain in power, specifically as you gain more health, it will take more of the burden off of me.",
"Which will allow me to recover much faster after the execute.",
"",
"I want you to know that I did discover how to fight these monsters just as you are.",
"The reason that I haven't told you yet is because I'm embarrassed to say that I am still much too weak.",
"Please know that I am getting closer with every monster you kill.",
"",
"Well that was all a bit heavy, and that other project is almost complete. So I will be back when it\'s ready.",
"Just keep powering up your attack when you can and things will start to become easier for you.",
"And don't forget to make use of my ability to execute.",
"Anyway, good luck for now.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ok! That was a bit complicated, but I have gathered as much information as I possibly could.",
"I hope that you find this to be useful.",
"As you already know, Green Slime are extinct, but once that happened I learned of a new threat.",
"When the last Green Slime was killed, rather than a decreased monster presence, I instead felt an increase.",
"I am not yet fully sure what this means, as they have not made themselves known.",
"Though I feel that we will find out soon enough.",
"But let us focus on right now, and worry about that when the time comes.",
"Also, I want you to know that your deeds are not going un-noticed.",
"It's clear that you are achieving a great deal here, and with my returning power I am thinking of ways to reward you further.",
"I just need a bit more clarity and time. Then I will have something that I think you will really like.",
"I have been working on this for a while, so it shouldn't take that much longer.",
"I do wish I had all of my power so I could just give you everything at once.",
"Here's an interesting fact about Tree.",
"None of them are hostile, but there is a monster called Mana Beast that empowers them and makes them fight.",
"They are still pretty weak though because, well,",
"They're wood.",
"Ok I should stop getting distracted, I need to finish putting this next thing together for you.",
"See you soon.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Alright, I think I have figured it out.",
"Since I have to go away at times, I put this together so you can be rewarded without me needing to intervene.",
"I am still working on the rest, but I wanted you to at least have these for now.",
"You don't need to understand what all of that means right now, it will become clear as you proceed.",
"Alright that took a lot of energy, so I must rest.",
"This time I want you to be more prepared for the next threat, so I will give you this advice.",
"Be mindful of your defense. If the monsters break through it, they will quickly take you down.",
"The next monster is stronger than you, so please watch your health.",
"You are competent and dedicated, so I am not too concerned.",
"The only problem is that it seems the monsters are always aware of your power, and adjust accordingly.",
"But either way, I am starting to become encouraged that there is still hope for this world.",
"Thank you.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hello, I am back and feeling much better.",
"How are you doing here? You must have encountered the Scorpion by now.",
"I hope you didn't get knocked out while I was gone.",
"I have learned something interesting that I didn't sense before.",
"There is a different kind of presence here as well, a neutral one.",
"I don't know exactly what it is, but it isn\'t evil.",
"It is coming very soon.",
"",
"",
"Oh of course, a Core Repository! Do you want me to execute it?",
"When monsters die naturally their cores are stored in those, kind of like a graveyard.",
"There is a huge amount of energy contained within them, and as more monsters die there will be more cores inside.",
"Opening that brought a lot of power back to me. I think I am finally ready to try attacking.",
"Just remove this monster and I will fight the next one.",
"",
"It worked! I am still very weak, but you can choose to empower me further with the cores you gain.",
"You will still gain from what I kill, the choice of how you want to proceed is entirely up to you.",
"If you decide to refocus your energy, I will give you back what you spent on me as well.",
"It does take a lot out of me to attack though, so I won't be able to communicate as frequently.",
"Now together we can really start bringing these monsters down and take back this world!",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
];

Game.variables.cathyAchievementsText = [
    "",
    "Hey congratulations! You accomplished everything that you set out to do here.",
    "I suppose that it is time to give you my final gift.",
    "You have done many great things, and worked tirelessly to take back this world.",
    "Our power has grown greatly, and my mind has cleared.",
    "Of course, we are still overrun, but the monsters are no longer constricting me.",
    "Though I must admit that the future here is not quite foreseeable.",
    "We may continue to grow in power, but so do they.",
    "This doesn't mean that we have failed or that we must give up.",
    "I have figured out a way that we might gain an advantage over them, but it comes with some complications.",
    "We can purge all of our power, and begin anew.",
    "Everything will be like it was when you first arrived, except for one significant difference.",
    "All of the gathered cores will be combined into a Super Core, empowering us beyond what we are now capable.",
    "The world that I created will still be here, but in our weakened state, all the monsters will be able to return.",
    "Except we will be much more prepared this time.",
    "I have made an entry in the log explaining this process in more detail.",
    "Just let me know when you are ready to transcend.",
    "If you want to wait and gather more power for the super core, there is no rush.",
    "Perhaps someday we can wipe this place completely clear of monsters.",
    "Or maybe this is our destiny, maybe there is a reason why they arrived here.",
    "Maybe I learned that being a god of an empty world was the worst fate possible.",
    "Is it really paradise if you have no one to share it with?",
    "Perhaps I needed to find a way to bring someone here. To give them a reason to join me.",
    "",
    "...",
    "Sorry! I got a little caught up in my thoughts just now. What were we talking about?",
    "Oh yes, transcendence.",
    "It reminds me of a Zen koan that I once heard.",
    "Do you care to hear it? Ok,",
    "How many clicks does it take to get to the core of a Green Slime?",
    ""
    //the end.
];

Game.variables.cathyBossText = [
    "Duel",
    "cboss1",
    "cboss2",
    "cboss3",
    "cboss4",
    "cboss6",
    "cboss7",
    "cboss8",
    "cboss9",
    "cboss10",
    "cboss11",
    "cboss12",
    "cboss13",
    "cboss14"
];

var monsterFlavor = [
    [ //green slime
        "Green Slime are native to any world that needs saving.",
        "Green Slime enjoys long walks on the beach.",
        "Do not eat Green Slime.",
        "",
        "What does the Green Slime say?",
        "How many Green Slime does it take to screw in a light bulb?",
        "1 Green Slime + 1 Green Slime = 2 Green Slime.",
        "No one knows where Green Slime originated from.",
        "",
        ""
    ],
    [ //red slime
        "Red Slime hobbies include: tennis, hockey, and checkers",
        "This Red Slime is celebrating its birthday today!",
        "A collective of Red Slime is called a Blob.",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //tree small
        "Tree\'s favorite foods are dirt and water.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //scorpion
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //boar
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //giant
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //gargoyle
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //bunny
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //mana beast
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //specter
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //dragon
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //green boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //red boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
   [ //tree boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //scorpion boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //boar boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //giant boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //gargoyle boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //bunny boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //mana boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //specter boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ //dragon boss
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ]
];


var chestSmallFlavor = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
];
var cathyBossFlavor = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
];
var chestLargeFlavor = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
];